---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omni-ui
  namespace: multi-agent
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: omni.ai-agent.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omni-ui
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finguard-ui
  namespace: finguard-customer
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: finguard.ai-agent.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finguard-ui-frontend
                port:
                  number: 80
