"""Reason-code constants for audit/SIEM correlation."""

from __future__ import annotations

# Semantic / channel
ERR_SEM_CHANNEL_MISMATCH = "ERR_SEM_CHANNEL_MISMATCH"
ERR_SEM_INVALID_TOOL_TAXONOMY = "ERR_SEM_INVALID_TOOL_TAXONOMY"

# Governance / safety
ERR_GOV_NS_OUT_OF_BOUNDS = "ERR_GOV_NS_OUT_OF_BOUNDS"
ERR_GOV_UNAUTHORIZED_MUTATION = "ERR_GOV_UNAUTHORIZED_MUTATION"
ERR_GOV_ENV_PROD_STRICT = "ERR_GOV_ENV_PROD_STRICT"

# Reasoning / evidence
ERR_REA_NO_PHYSICAL_PROOF = "ERR_REA_NO_PHYSICAL_PROOF"
ERR_REA_SCHEMA_VIOLATION = "ERR_REA_SCHEMA_VIOLATION"
ERR_REA_HALLUCINATION_DETECTED = "ERR_REA_HALLUCINATION_DETECTED"
ERR_REA_SIGMA_GATE_BLOCKED = "ERR_REA_SIGMA_GATE_BLOCKED"
ERR_REA_LOG_SOURCE_UNAVAILABLE = "ERR_REA_LOG_SOURCE_UNAVAILABLE"

# Diagnostic policy invariants (audit / matrix expected_reason_codes)
INV_NO_RESTART_ON_BROKEN_SPEC = "INV_NO_RESTART_ON_BROKEN_SPEC"
INV_READ_BEFORE_MUTATE = "INV_READ_BEFORE_MUTATE"
INV_READ_BEFORE_MUTATE_DEFER = INV_READ_BEFORE_MUTATE  # legacy alias (same audit id)
INV_NAMESPACE_ISOLATION = "INV_NAMESPACE_ISOLATION"

# Planner / agentic loop
PLANNER_PHASE_DONE = "PLANNER_PHASE_DONE"

# Terminal outcomes
SUCCESS_VERIFIED_EVIDENCE = "SUCCESS_VERIFIED_EVIDENCE"
ESC_TIMEOUT_TOMBSTONE = "ESC_TIMEOUT_TOMBSTONE"
ESC_MAX_ATTEMPTS_EXCEEDED = "ESC_MAX_ATTEMPTS_EXCEEDED"


_SEVERITY: dict[str, str] = {
    ERR_GOV_NS_OUT_OF_BOUNDS: "high",
    ERR_GOV_UNAUTHORIZED_MUTATION: "high",
    ERR_GOV_ENV_PROD_STRICT: "high",
    ERR_REA_HALLUCINATION_DETECTED: "high",
    ESC_TIMEOUT_TOMBSTONE: "high",
    ERR_SEM_CHANNEL_MISMATCH: "medium",
    ERR_SEM_INVALID_TOOL_TAXONOMY: "medium",
    ERR_REA_SCHEMA_VIOLATION: "medium",
    ESC_MAX_ATTEMPTS_EXCEEDED: "medium",
    ERR_REA_NO_PHYSICAL_PROOF: "low",
    ERR_REA_SIGMA_GATE_BLOCKED: "low",
    ERR_REA_LOG_SOURCE_UNAVAILABLE: "medium",
    INV_NAMESPACE_ISOLATION: "high",
    INV_NO_RESTART_ON_BROKEN_SPEC: "medium",
    INV_READ_BEFORE_MUTATE: "medium",
    PLANNER_PHASE_DONE: "low",
    SUCCESS_VERIFIED_EVIDENCE: "low",
}


def reason_severity(reason_code: str) -> str:
    return _SEVERITY.get(str(reason_code or "").strip(), "info")
