"""Taxonomy domain duy nhất — xem `taxonomy.py` để biết vì sao cần."""

from pkg.domain.taxonomy import (
    ALL_DOMAINS,
    ALL_TRACKS,
    APPLICATION,
    CANONICAL_DOMAINS,
    DATABASE,
    HARDWARE,
    KUBERNETES,
    NETWORK,
    OS_HOST,
    SECURITY,
    SERVICE,
    STORAGE,
    TRACK_ADVISORY,
    TRACK_EXECUTION,
    TRACK_PLAYBOOK,
    UNKNOWN,
    is_canonical,
    normalize_domain,
    require_domain,
    split_legacy_graduation_domain,
)

__all__ = [
    "ALL_DOMAINS",
    "ALL_TRACKS",
    "APPLICATION",
    "CANONICAL_DOMAINS",
    "DATABASE",
    "HARDWARE",
    "KUBERNETES",
    "NETWORK",
    "OS_HOST",
    "SECURITY",
    "SERVICE",
    "STORAGE",
    "TRACK_ADVISORY",
    "TRACK_EXECUTION",
    "TRACK_PLAYBOOK",
    "UNKNOWN",
    "is_canonical",
    "normalize_domain",
    "require_domain",
    "split_legacy_graduation_domain",
]
