"""Stable CRAT ``event_type`` strings for producers and gateway ordering."""

from __future__ import annotations

CRAT_EVENT_ADVISORY_DECISION = "ADVISORY_DECISION"
CRAT_EVENT_ADVISORY_DISPATCHED = "ADVISORY_DISPATCHED"
CRAT_EVENT_MUTATION_TRAPPED = "MUTATION_TRAPPED"
CRAT_EVENT_HITL_DECISION = "HITL_DECISION"
CRAT_EVENT_MUTATION_ENQUEUED = "MUTATION_ENQUEUED"
CRAT_EVENT_MUTATION_ENQUEUE_FAILED = "MUTATION_ENQUEUE_FAILED"
CRAT_EVENT_ROLLBACK_EXECUTED = "ROLLBACK_EXECUTED"  # S1.2
CRAT_EVENT_SOP_PROMOTED = "SOP_PROMOTED"  # S2.2
CRAT_EVENT_AUTONOMY_TIER_CHANGED = "AUTONOMY_TIER_CHANGED"  # Autonomy tier (MASTER_PLAN §7)
CRAT_EVENT_CONFIG_CHANGED = "CONFIG_CHANGED"  # Admin UI config write (runtime_flag/risk_class/tenant)
# L4 playbook-first (K8s-first; domain-agnostic schema)
CRAT_EVENT_PLAYBOOK_EXECUTED = "PLAYBOOK_EXECUTED"
CRAT_EVENT_PLAYBOOK_PROOF_FAILED = "PLAYBOOK_PROOF_OF_FAULT_FAILED"
CRAT_EVENT_PLAYBOOK_GRADUATED = "PLAYBOOK_GRADUATED"
CRAT_EVENT_PLAYBOOK_DEMOTED = "PLAYBOOK_DEMOTED"
CRAT_EVENT_CIRCUIT_BREAKER_TRIPPED = "CIRCUIT_BREAKER_TRIPPED"
