#!/usr/bin/env python3
"""Sync official vendor docs into local repo for offline-first lookup."""

from __future__ import annotations

import argparse
import json
import re
import urllib.error
import urllib.parse
import urllib.request
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


DEFAULT_MANIFEST = Path("docs/vendor/sources.json")
DEFAULT_TIMEOUT = 25


def _slug_from_url(url: str) -> str:
    parsed = urllib.parse.urlparse(url)
    host = parsed.netloc.replace(".", "_")
    path = parsed.path.strip("/")
    if not path:
        path = "index"
    path = re.sub(r"[^a-zA-Z0-9/_-]+", "-", path).strip("-")
    path = path.replace("/", "__")
    return f"{host}__{path}.html"


def _fetch(url: str, timeout_s: int) -> str:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "multi-agent-system-doc-sync/1.0 (+offline-local-mirror)",
            "Accept": "text/html, text/markdown, text/plain;q=0.9, */*;q=0.8",
        },
    )
    with urllib.request.urlopen(req, timeout=timeout_s) as resp:
        content = resp.read()
    return content.decode("utf-8", errors="replace")


def _write_vendor_index(vendor_dir: Path, vendor_name: str, pages: list[dict[str, str]]) -> None:
    lines = [
        f"# {vendor_name} (Local Mirror)",
        "",
        "Generated by `scripts/sync_vendor_docs.py`.",
        "",
        "| Local file | Source URL | Synced at (UTC) |",
        "|---|---|---|",
    ]
    for p in pages:
        lines.append(f"| `{p['file']}` | {p['url']} | {p['synced_at']} |")
    lines.append("")
    (vendor_dir / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def sync_docs(manifest_path: Path, timeout_s: int) -> tuple[int, int]:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    vendors = data.get("vendors", [])
    if not isinstance(vendors, list):
        raise ValueError("Invalid manifest format: `vendors` must be a list")

    ok = 0
    fail = 0
    now = datetime.now(UTC).isoformat()

    for vendor in vendors:
        if not isinstance(vendor, dict):
            continue
        vendor_name = str(vendor.get("name", vendor.get("id", "vendor")))
        base_dir = Path(str(vendor.get("base_dir", "")))
        pages = vendor.get("pages", [])
        if not base_dir or not isinstance(pages, list):
            continue

        base_dir.mkdir(parents=True, exist_ok=True)
        index_pages: list[dict[str, str]] = []

        for url in pages:
            if not isinstance(url, str) or not url.startswith(("http://", "https://")):
                continue
            output_name = _slug_from_url(url)
            output_path = base_dir / output_name
            try:
                content = _fetch(url, timeout_s=timeout_s)
                output_path.write_text(content, encoding="utf-8")
                ok += 1
                index_pages.append({"file": output_name, "url": url, "synced_at": now})
                print(f"[OK] {vendor_name}: {url}")
            except (urllib.error.URLError, TimeoutError, OSError) as exc:
                fail += 1
                print(f"[FAIL] {vendor_name}: {url} :: {exc}")

        _write_vendor_index(base_dir, vendor_name, index_pages)

    return ok, fail


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync official vendor docs for offline lookup.")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST), help="Path to docs sources JSON.")
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT, help="HTTP timeout seconds.")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"Manifest not found: {manifest_path}")
        return 2

    ok, fail = sync_docs(manifest_path=manifest_path, timeout_s=args.timeout)
    print(f"Done. success={ok}, failed={fail}")
    return 1 if fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
