"""Compatibility shim — Postgres/pgvector removed; re-exports from redis_vector_store."""
# All callers that still import from here continue to work unchanged.
from rag.redis_vector_store import (  # noqa: F401
    COLLECTION_ACTION_EXPERIENCE,
    COLLECTION_CLI_HIL_CONTEXT,
    COLLECTION_ERRORS,
    COLLECTION_INFRA_TOPOLOGY,
    COLLECTION_K8S_EXPERT,
    COLLECTION_SOP,
    COLLECTION_SOP_V2,
    COLLECTION_SRE_KNOWLEDGE,
    COLLECTION_VENDOR_KNOWLEDGE,
    EMBED_DIM,
    PGVectorStore,
    PointStruct,
    PostgresRAGSettings,
    QueryResponse,
    RedisVectorStore,
    RedisRAGSettings,
    _stable_vec_from_text,
    init_pg_pool,
    log_error_to_ledger,
)

__all__ = [
    "COLLECTION_ACTION_EXPERIENCE",
    "COLLECTION_CLI_HIL_CONTEXT",
    "COLLECTION_ERRORS",
    "COLLECTION_INFRA_TOPOLOGY",
    "COLLECTION_K8S_EXPERT",
    "COLLECTION_SOP",
    "COLLECTION_SOP_V2",
    "COLLECTION_SRE_KNOWLEDGE",
    "COLLECTION_VENDOR_KNOWLEDGE",
    "EMBED_DIM",
    "PGVectorStore",
    "PointStruct",
    "PostgresRAGSettings",
    "QueryResponse",
    "RedisVectorStore",
    "RedisRAGSettings",
    "init_pg_pool",
    "log_error_to_ledger",
]
